apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: integrations-label-maker
  namespace: integrations
  labels:
    integrations: label-maker
    environment: dev
spec:
  replicas: 1
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 300
  minReadySeconds: 60
  selector:
    matchLabels:
      integrations: label-maker
      environment: dev
  template:
    metadata:
      labels:
        integrations: label-maker
        environment: dev
    spec:
      containers:
      - name: integrations-label-maker
        image: 813448775391.dkr.ecr.us-east-1.amazonaws.com/integrations-label-maker:<SED_IMAGE_TAG_HERE>
        ports:
        - containerPort: 3000
        readinessProbe:
          initialDelaySeconds: 5
          timeoutSeconds: 2
          httpGet:
            path: /template/sample.ejs
            port: 3000