kind: Service
apiVersion: v1
metadata:
  name: integrations-label-maker
  namespace: integrations
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:813448775391:certificate/cb992753-2b8d-4de2-8400-0bef310a6282
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    external-dns.alpha.kubernetes.io/hostname: label-maker-dev.kube.sslocal.com.
spec:
  selector:
    integrations: label-maker
    environment: dev
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 3000
  type: LoadBalancer